version: '3'
services:
  nodejs-server:
    container_name: backend_nodejs
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    depends_on:
      - "postgres"
    networks:
      - reactjs-network
  react:
    container_name: frontend_reactjs
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    networks:
      - reactjs-network
    depends_on:
      - "nodejs-server"
  postgres:
    container_name: database_postgres
    build: ./database
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/:/var/lib/postgresql/data
      - ./database/backups/:/backups
    networks:
      - reactjs-network
  pgadmin:
    container_name: SGBD_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "joao@email.com.br"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - "postgres"
    networks:
      - reactjs-network
volumes:
    persistent:
networks: 
  reactjs-network:
    driver: bridge